# Generated by Django 6.0.6 on 2026-06-29 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal name of the company.', max_length=200, verbose_name='company name')),
                ('tax_id', models.CharField(db_index=True, help_text='Tax identification number (NIT, RUC, CIF, etc.).', max_length=50, unique=True, verbose_name='tax ID')),
                ('email', models.EmailField(help_text='Primary contact email for the company.', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Primary phone number.', max_length=20, verbose_name='phone')),
                ('website', models.URLField(blank=True, help_text='Company website URL.', verbose_name='website')),
                ('industry', models.CharField(blank=True, help_text='Industry or business sector.', max_length=100, verbose_name='industry')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='PROSPECT', help_text='Current status of the company in the CRM.', max_length=20, verbose_name='status')),
                ('address', models.TextField(blank=True, help_text='Physical address of the company.', verbose_name='address')),
                ('city', models.CharField(blank=True, help_text='City.', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, help_text='State or province.', max_length=100, verbose_name='state/province')),
                ('country', models.CharField(default='Unknown', help_text='Country.', max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, help_text='Postal or ZIP code.', max_length=20, verbose_name='postal code')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the company.', verbose_name='notes')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'crm_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name.', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Last name.', max_length=100, verbose_name='last name')),
                ('email', models.EmailField(help_text='Contact email address.', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, help_text='Mobile phone number.', max_length=20, verbose_name='mobile')),
                ('position', models.CharField(blank=True, help_text='Job title or position.', max_length=100, verbose_name='position')),
                ('department', models.CharField(blank=True, help_text='Department within the company.', max_length=100, verbose_name='department')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Undisclosed')], help_text='Gender.', max_length=1, verbose_name='gender')),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates if this is the primary contact for the company.', verbose_name='primary contact')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the contact.', verbose_name='notes')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'crm_contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Phone Call'), ('MEETING', 'Meeting'), ('NOTE', 'Note'), ('TASK', 'Task'), ('SUPPORT_TICKET', 'Support Ticket'), ('OTHER', 'Other')], help_text='Type of interaction.', max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='COMPLETED', help_text='Status of the interaction.', max_length=20, verbose_name='status')),
                ('subject', models.CharField(blank=True, help_text='Brief subject or title of the interaction.', max_length=200, verbose_name='subject')),
                ('description', models.TextField(help_text='Detailed description of the interaction.', verbose_name='description')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled date and time for the interaction.', null=True, verbose_name='scheduled at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Actual completion date and time.', null=True, verbose_name='completed at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'interaction',
                'verbose_name_plural': 'interactions',
                'db_table': 'crm_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
