# Generated by Django 6.0.6 on 2026-06-29 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Sales representative or account owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(help_text='Company this contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='company',
            field=models.ForeignKey(help_text='Company related to this interaction.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Specific contact involved in this interaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.contact', verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(help_text='User who logged this interaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', '-created_at'], name='crm_compani_status_b0b348_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner', '-created_at'], name='crm_compani_owner_i_e73c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'is_primary'], name='crm_contact_company_64a1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_75ee32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['company', '-created_at'], name='crm_interac_company_f33c25_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['contact', '-created_at'], name='crm_interac_contact_d90a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['type', '-created_at'], name='crm_interac_type_0a784e_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['status', '-created_at'], name='crm_interac_status_cd2d14_idx'),
        ),
    ]
