# Generated by Django 6.0.6 on 2026-06-29 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice number.', max_length=50, unique=True, verbose_name='invoice number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='DRAFT', help_text='Current status of the invoice.', max_length=20, verbose_name='status')),
                ('issue_date', models.DateField(help_text='Date when the invoice was issued.', verbose_name='issue date')),
                ('due_date', models.DateField(help_text='Date when the invoice is due.', verbose_name='due date')),
                ('paid_date', models.DateField(blank=True, help_text='Date when the invoice was paid.', null=True, verbose_name='paid date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal before taxes and discounts.', max_digits=10, verbose_name='subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate percentage.', max_digits=5, verbose_name='tax rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax amount.', max_digits=10, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount applied.', max_digits=10, verbose_name='discount amount')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount due.', max_digits=10, verbose_name='total')),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217).', max_length=3, verbose_name='currency')),
                ('billing_period_start', models.DateField(blank=True, help_text='Start date of the billing period.', null=True, verbose_name='billing period start')),
                ('billing_period_end', models.DateField(blank=True, help_text='End date of the billing period.', null=True, verbose_name='billing period end')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the invoice.', verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
                ('pdf_path', models.CharField(blank=True, help_text='Path to the generated PDF invoice.', max_length=500, verbose_name='PDF path')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'db_table': 'billing_invoices',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the item.', max_length=500, verbose_name='description')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of items.', verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit.', max_digits=10, verbose_name='unit price')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount for this line item.', max_digits=10, verbose_name='amount')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
                'db_table': 'billing_invoice_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount.', max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217).', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', help_text='Status of the payment.', max_length=20, verbose_name='status')),
                ('provider_payment_id', models.CharField(blank=True, help_text='Payment ID in the payment provider system.', max_length=100, verbose_name='provider payment ID')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date and time when the payment was processed.', null=True, verbose_name='processed at')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure if applicable.', verbose_name='failure reason')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'billing_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], help_text='Type of payment method.', max_length=20, verbose_name='type')),
                ('provider', models.CharField(help_text='Payment provider (e.g., Stripe, PayPal).', max_length=50, verbose_name='provider')),
                ('provider_customer_id', models.CharField(blank=True, help_text='Customer ID in the payment provider system.', max_length=100, verbose_name='provider customer ID')),
                ('provider_payment_method_id', models.CharField(blank=True, help_text='Payment method ID in the payment provider system.', max_length=100, verbose_name='provider payment method ID')),
                ('last_four', models.CharField(blank=True, help_text='Last four digits of card or account number.', max_length=4, verbose_name='last four digits')),
                ('brand', models.CharField(blank=True, help_text='Card brand or bank name.', max_length=50, verbose_name='brand')),
                ('exp_month', models.PositiveIntegerField(blank=True, help_text='Expiration month (1-12).', null=True, verbose_name='expiration month')),
                ('exp_year', models.PositiveIntegerField(blank=True, help_text='Expiration year.', null=True, verbose_name='expiration year')),
                ('is_default', models.BooleanField(default=False, help_text='Indicates if this is the default payment method.', verbose_name='default')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this payment method is active.', verbose_name='active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'db_table': 'billing_payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', help_text='Current status of the subscription.', max_length=20, verbose_name='status')),
                ('provider_subscription_id', models.CharField(blank=True, help_text='Subscription ID in the payment provider system.', max_length=100, verbose_name='provider subscription ID')),
                ('current_period_start', models.DateTimeField(help_text='Start date of the current billing period.', verbose_name='current period start')),
                ('current_period_end', models.DateTimeField(help_text='End date of the current billing period.', verbose_name='current period end')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Indicates if subscription will cancel at period end.', verbose_name='cancel at period end')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='Date when the subscription was canceled.', null=True, verbose_name='canceled at')),
                ('trial_start', models.DateTimeField(blank=True, help_text='Start date of trial period.', null=True, verbose_name='trial start')),
                ('trial_end', models.DateTimeField(blank=True, help_text='End date of trial period.', null=True, verbose_name='trial end')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'billing_subscriptions',
                'ordering': ['-current_period_end'],
            },
        ),
    ]
