# Generated by Django 6.0.6 on 2026-06-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('crm', '0001_initial'),
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(help_text='Company being billed.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(help_text='Company that made the payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice associated with this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice', verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(help_text='Company that owns this payment method.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='crm.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(help_text='Payment method used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.paymentmethod', verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Payment method used for this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.paymentmethod', verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(help_text='Company with the subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='crm.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(help_text='Payment method for recurring payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.paymentmethod', verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(help_text='Plan being subscribed to.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='licensing.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription associated with this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription', verbose_name='subscription'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['company', 'is_active'], name='billing_pay_company_e3ebf4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['provider', 'provider_customer_id'], name='billing_pay_provide_12ee02_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status'], name='billing_inv_company_15b125_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_inv_status_24aad0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_1d4853_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'status'], name='billing_sub_company_a3a095_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'current_period_end'], name='billing_sub_status_7f7f12_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', '-created_at'], name='billing_pay_company_7487e3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='billing_pay_status_d52bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', '-created_at'], name='billing_pay_invoice_fb9795_idx'),
        ),
    ]
