# Generated by Django 6.0.6 on 2026-06-29 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the plan.', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of the plan features.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the plan is available for purchase.', verbose_name='active')),
                ('max_users', models.PositiveIntegerField(default=1, help_text='Maximum number of users allowed.', verbose_name='max users')),
                ('max_licenses', models.PositiveIntegerField(default=1, help_text='Maximum number of concurrent licenses.', verbose_name='max licenses')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Duration of the plan in days (0 for lifetime).', verbose_name='duration (days)')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('LIFETIME', 'Lifetime')], default='MONTHLY', help_text='Billing cycle for recurring payments.', max_length=20, verbose_name='billing cycle')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per billing cycle.', max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217).', max_length=3, verbose_name='currency')),
                ('modules', models.JSONField(default=list, help_text='List of module codes included in this plan.', verbose_name='modules')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Additional features and their limits in JSON format.', verbose_name='features')),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Number of trial days (0 for no trial).', verbose_name='trial days')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'licensing_plans',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['is_active', 'billing_cycle'], name='licensing_p_is_acti_ca5125_idx')],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, help_text='Unique license key (UUID or custom format).', max_length=64, unique=True, verbose_name='license key')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the license.', max_length=20, verbose_name='status')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Date and time when the license was first activated.', null=True, verbose_name='activated at')),
                ('starts_at', models.DateTimeField(help_text='License start date.', verbose_name='starts at')),
                ('expires_at', models.DateTimeField(help_text='License expiration date.', verbose_name='expires at')),
                ('last_validated_at', models.DateTimeField(blank=True, help_text='Last time the license was validated.', null=True, verbose_name='last validated at')),
                ('validation_count', models.PositiveIntegerField(default=0, help_text='Number of times the license has been validated.', verbose_name='validation count')),
                ('max_activations', models.PositiveIntegerField(default=1, help_text='Maximum number of allowed activations.', verbose_name='max activations')),
                ('current_activations', models.PositiveIntegerField(default=0, help_text='Current number of active installations.', verbose_name='current activations')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
                ('signature', models.TextField(blank=True, help_text='Digital signature of the license data.', verbose_name='signature')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this license.', verbose_name='notes')),
                ('company', models.ForeignKey(help_text='Company that owns this license.', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='crm.company', verbose_name='company')),
                ('plan', models.ForeignKey(help_text='Plan associated with this license.', on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'licenses',
                'db_table': 'licensing_licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(help_text='Unique identifier of the machine/device.', max_length=100, verbose_name='machine ID')),
                ('machine_name', models.CharField(blank=True, help_text='Friendly name of the machine/device.', max_length=200, verbose_name='machine name')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the activation was made.', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the activation request.', verbose_name='user agent')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this activation is currently active.', verbose_name='active')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Date and time when the activation was deactivated.', null=True, verbose_name='deactivated at')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this activation communicated with the server.', null=True, verbose_name='last seen at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the activation in JSON format.', verbose_name='metadata')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licensing.license', verbose_name='license')),
            ],
            options={
                'verbose_name': 'license activation',
                'verbose_name_plural': 'license activations',
                'db_table': 'licensing_activations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license', 'is_active'], name='licensing_a_license_37424f_idx'), models.Index(fields=['machine_id'], name='licensing_a_machine_bceb21_idx')],
                'unique_together': {('license', 'machine_id')},
            },
        ),
        migrations.CreateModel(
            name='LicenseUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='Name of the metric being tracked.', max_length=100, verbose_name='metric name')),
                ('metric_value', models.BigIntegerField(help_text='Value of the metric at the time of recording.', verbose_name='metric value')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the metric was recorded.', verbose_name='recorded at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='licensing.license', verbose_name='license')),
            ],
            options={
                'verbose_name': 'license usage',
                'verbose_name_plural': 'license usage records',
                'db_table': 'licensing_usage',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['license', 'metric_name', '-recorded_at'], name='licensing_u_license_ea63c7_idx'), models.Index(fields=['recorded_at'], name='licensing_u_recorde_f323aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['status', '-created_at'], name='licensing_l_status_9f8764_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['company', 'status'], name='licensing_l_company_c19340_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['expires_at'], name='licensing_l_expires_f4f21a_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_key'], name='licensing_l_license_f07a76_idx'),
        ),
    ]
