# Generated by Django 6.0.6 on 2026-06-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseactivation',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this specific activation was performed.', null=True, verbose_name='activated at'),
        ),
    ]
