# Generated by Django 6.0.6 on 2026-06-29 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Required. A valid email address.', max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='Optional phone number.', max_length=20, null=True, verbose_name='phone number')),
                ('avatar', models.ImageField(blank=True, help_text='Optional user avatar image.', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the user email has been verified.', verbose_name='verified')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Date and time of the last login.', null=True, verbose_name='last login at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'auth_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the menu item.', max_length=100, verbose_name='name')),
                ('icon', models.CharField(blank=True, help_text='Icon class or name for the menu item.', max_length=50, verbose_name='icon')),
                ('url', models.CharField(blank=True, help_text='URL or route path for the menu item.', max_length=200, verbose_name='url')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the menu item within its parent.', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the menu item is visible.', verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item for hierarchical structure.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='iam.menu', verbose_name='parent menu')),
                ('required_permissions', models.ManyToManyField(blank=True, help_text='Permissions required to view this menu item.', related_name='menus', to='auth.permission', verbose_name='required permissions')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'iam_menus',
                'ordering': ['parent__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the role.', max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of the role and its purpose.', verbose_name='description')),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted or modified.', verbose_name='system role')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions assigned to this role.', related_name='roles', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'iam_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_CHANGE', 'Permission Change'), ('ROLE_ASSIGN', 'Role Assign'), ('LICENSE_GENERATE', 'License Generate'), ('LICENSE_VALIDATE', 'License Validate'), ('DOCUMENT_SIGN', 'Document Sign'), ('OTHER', 'Other')], help_text='Type of action performed.', max_length=50, verbose_name='action')),
                ('resource_type', models.CharField(help_text='Type of resource affected (e.g., User, License, Document).', max_length=100, verbose_name='resource type')),
                ('resource_id', models.UUIDField(blank=True, help_text='ID of the affected resource.', null=True, verbose_name='resource id')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed.', null=True, verbose_name='ip address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request.', verbose_name='user agent')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action in JSON format.', verbose_name='details')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending')], default='SUCCESS', help_text='Status of the action.', max_length=20, verbose_name='status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'db_table': 'iam_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='iam_audit_l_user_id_1126af_idx'), models.Index(fields=['resource_type', 'resource_id'], name='iam_audit_l_resourc_1a51dc_idx'), models.Index(fields=['action', '-created_at'], name='iam_audit_l_action_485e0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this role assignment.', null=True, verbose_name='expires at')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='iam.role', verbose_name='role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
                'db_table': 'iam_user_roles',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
