# Generated by Django 6.0.6 on 2026-06-29 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the key pair.', max_length=100, verbose_name='name')),
                ('algorithm', models.CharField(choices=[('ED25519', 'Ed25519'), ('RSA_2048', 'RSA 2048'), ('RSA_4096', 'RSA 4096')], default='ED25519', help_text='Cryptographic algorithm used for this key pair.', max_length=20, verbose_name='algorithm')),
                ('purpose', models.CharField(choices=[('LICENSE', 'License Signing'), ('DOCUMENT', 'Document Signing'), ('GENERAL', 'General Purpose')], default='GENERAL', help_text='Intended purpose of this key pair.', max_length=20, verbose_name='purpose')),
                ('public_key', models.TextField(help_text='Public key in PEM format.', verbose_name='public key')),
                ('private_key_encrypted', models.TextField(help_text='Private key encrypted with master key in PEM format.', verbose_name='private key (encrypted)')),
                ('fingerprint', models.CharField(db_index=True, help_text='SHA-256 fingerprint of the public key.', max_length=64, unique=True, verbose_name='fingerprint')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this key pair is currently active.', verbose_name='active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the key pair.', null=True, verbose_name='expires at')),
                ('created_by', models.ForeignKey(help_text='User who created this key pair.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signing_keys', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner', models.ForeignKey(help_text='Company or entity that owns this key pair.', on_delete=django.db.models.deletion.CASCADE, related_name='signing_keys', to='crm.company', verbose_name='owner')),
                ('user', models.ForeignKey(blank=True, help_text='Specific user associated with this key (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_keys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'signing key',
                'verbose_name_plural': 'signing keys',
                'db_table': 'signing_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LICENSE', 'License'), ('DOCUMENT', 'Document'), ('DATA', 'Data'), ('OTHER', 'Other')], help_text='Type of content being signed.', max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending')], default='SUCCESS', help_text='Status of the signing operation.', max_length=20, verbose_name='status')),
                ('original_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the original content.', max_length=64, verbose_name='original hash')),
                ('signature_value', models.TextField(help_text='Digital signature in base64 format.', verbose_name='signature value')),
                ('signed_content', models.BinaryField(blank=True, help_text='Original content or reference to it (optional).', null=True, verbose_name='signed content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the signature in JSON format.', verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the signature was requested.', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the signature request.', verbose_name='user agent')),
                ('signer', models.ForeignKey(help_text='User who requested the signature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signatures', to=settings.AUTH_USER_MODEL, verbose_name='signer')),
                ('signing_key', models.ForeignKey(help_text='Key pair used to create this signature.', on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='signing.signingkey', verbose_name='signing key')),
            ],
            options={
                'verbose_name': 'signature',
                'verbose_name_plural': 'signatures',
                'db_table': 'signing_signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the document.', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Description of the document.', verbose_name='description')),
                ('file_path', models.CharField(help_text='Path or URL to the stored document file.', max_length=500, verbose_name='file path')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the document file.', max_length=64, verbose_name='file hash')),
                ('file_size', models.BigIntegerField(default=0, help_text='Size of the document file in bytes.', verbose_name='file size')),
                ('mime_type', models.CharField(default='application/octet-stream', help_text='MIME type of the document.', max_length=100, verbose_name='MIME type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURE', 'Pending Signature'), ('SIGNED', 'Signed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', help_text='Current status of the document.', max_length=30, verbose_name='status')),
                ('requires_signature', models.BooleanField(default=True, help_text='Indicates if the document requires a digital signature.', verbose_name='requires signature')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Date and time when the document was signed.', null=True, verbose_name='signed at')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when the signature was verified.', null=True, verbose_name='verified at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.', verbose_name='metadata')),
                ('company', models.ForeignKey(help_text='Company that owns this document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'signing_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='signing_doc_company_57f073_idx'), models.Index(fields=['file_hash'], name='signing_doc_file_ha_5ef399_idx'), models.Index(fields=['status', '-created_at'], name='signing_doc_status_5cd56a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='signingkey',
            index=models.Index(fields=['owner', 'is_active'], name='signing_key_owner_i_dd6a46_idx'),
        ),
        migrations.AddIndex(
            model_name='signingkey',
            index=models.Index(fields=['fingerprint'], name='signing_key_fingerp_54df7b_idx'),
        ),
        migrations.AddIndex(
            model_name='signingkey',
            index=models.Index(fields=['purpose', 'is_active'], name='signing_key_purpose_452ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['signing_key', '-created_at'], name='signing_sig_signing_ae60b1_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['original_hash'], name='signing_sig_origina_8f9f81_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['type', '-created_at'], name='signing_sig_type_fb5448_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['signer', '-created_at'], name='signing_sig_signer__40cf9c_idx'),
        ),
    ]
